<eclipse>
<message date="6/11/1997" time="0.00000000000000">
 OPTIONS(78) HAS BEEN SET TO USE                                         
 SCRATCH FILES FOR NNCS                                                  
</message>
<message date="6/11/1997" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="6/11/1997" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      47684 KBYTES                                                       
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      2 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      3 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      3 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      4 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      4 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      4 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      5 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      5 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      5 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      5 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      6 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      6 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      6 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      6 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      6 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      7 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      7 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      7 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      7 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      7 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      7 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      8 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS      9 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     10 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     11 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     12 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     13 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     14 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     15 AND     14                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND     14                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     16 AND     15                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     14                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     15                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     17 AND     16                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     14                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     15                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     16                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     18 AND     17                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     14                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     15                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     16                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     17                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     19 AND     18                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      1                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      2                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      3                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      4                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      5                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      6                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      7                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      8                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND      9                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     10                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     11                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     12                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     13                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     14                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     15                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     16                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     17                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     18                              
</message>
<message date="6/11/1997" time="0.00000000000000">
  THE FLUXNUM ARRAY WILL BE USED WITH THE MULTREGT                       
  KEYWORD BETWEEN REGIONS     20 AND     19                              
</message>
<message date="6/11/1997" time="0.00000000000000">
   1598   PINCH-OUT CONNECTIONS GENERATED                                
</message>
<message date="6/11/1997" time="0.00000000000000">
   2092 NON-NEIGHBOUR CONNECTIONS NNCS HAVE BEEN                         
 DELETED SINCE THEY HAVE ZERO TRANSMISSIBILITY                           
</message>
<message date="6/11/1997" time="0.00000000000000">
 PRE-PROCESSING HAS FOUND     1598 NON-NEIGHBOUR CONNECTIONS             
 WHICH EITHER JOIN ADJACENT CELLS OR CAN BE TREATED AS A                 
 NORMAL CONNECTION. THE TRANSMISSIBILITY HAS BEEN ADDED TO               
 THE APPROPRIATE CELL TRANSMISSIBILITY AND THE                           
 NON-NEIGHBOUR CONNECTION REMOVED FROM THE SIMULATION                    
</message>
<message date="6/11/1997" time="0.00000000000000">
 A FULL LISTING OF THESE NNCS CAN BE OBTAINED BY SETTING                 
 THE ALLNNC MNEMONIC IN RPTGRID. THE OUTPUT HAS THE                      
 TITLE MNEMONIC DEL-NNC                                                  
</message>
<warning date="6/11/1997" time="0.00000000000000">
 A TOTAL OF 496 CELLS HAVE BECOME INACTIVE BECAUSE                       
 THEY HAD A PORE VOLUME LESS THAN THAT SUPPLIED VIA THE                  
 MINPV OR MINPVV KEYWORDS IN THE GRID SECTION.                           
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 THE TOTAL PORE VOLUME HAS BEEN REDUCED BY  1.492E-02 PERCENT            
 BECAUSE CELLS BELOW THE THRESHOLD PORE VOLUME HAVE BEEN                 
 REMOVED FROM THE MODEL BY MINPV OR MINPVV                               
</warning>
<message date="6/11/1997" time="0.00000000000000">
 11363 NON-NEIGHBOUR CONNECTIONS PRESENT                                 
</message>
<message date="6/11/1997" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 44431                                         
</message>
<message date="6/11/1997" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     138732 KBYTES                                                       
</message>
<message date="6/11/1997" time="0.00000000000000">
    73310 CHARACTER VARIABLES USED                                       
</message>
<warning date="6/11/1997" time="0.00000000000000">
 TRACER NAMES STARTING WITH A BLANK SPACE OR ANY OF THE                  
 CHARACTERS F, S OR T ARE NOT RECOMMENDED SINCE THIS MAY CREATE          
 NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER: 'SEA'                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 TRACER NAMES STARTING WITH A BLANK SPACE OR ANY OF THE                  
 CHARACTERS F, S OR T ARE NOT RECOMMENDED SINCE THIS MAY CREATE          
 NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER: 'S36'                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 TRACER NAMES STARTING WITH A NUMBER ARE NOT RECOMMENDED SINCE           
 THIS MAY CREATE NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER:         
 '2FB'                                                                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 TRACER NAMES STARTING WITH A NUMBER ARE NOT RECOMMENDED SINCE           
 THIS MAY CREATE NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER:         
 '4FB'                                                                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 TRACER NAMES STARTING WITH A BLANK SPACE OR ANY OF THE                  
 CHARACTERS F, S OR T ARE NOT RECOMMENDED SINCE THIS MAY CREATE          
 NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER: 'TFB'                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
  THRESHOLD PRESSURE FROM REGION      2                                  
  TO REGION     1                                                        
  HAS ALREADY BEEN SPECIFIED                                             
  WILL BE OVER-WRITTEN                                                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
  THRESHOLD PRESSURE FROM REGION      3                                  
  TO REGION     1                                                        
  HAS ALREADY BEEN SPECIFIED                                             
  WILL BE OVER-WRITTEN                                                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
  THRESHOLD PRESSURE FROM REGION      4                                  
  TO REGION     1                                                        
  HAS ALREADY BEEN SPECIFIED                                             
  WILL BE OVER-WRITTEN                                                   
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 THE SWATINIT ARRAY IS IGNORED WHEN USING                                
 ENUMERATION TO DEFINE THE INITIAL SOLUTION                              
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 NO REGIONS WERE SPECIFIED FOLLOWING RGFT                                
 KEYWORD HAS BEEN IGNORED                                                
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 NO REGIONS WERE SPECIFIED FOLLOWING RWFT                                
 KEYWORD HAS BEEN IGNORED                                                
</warning>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD ROIP_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD ROIP_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RPR__GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RPR__NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD ROPR_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD ROPT_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD ROPR_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD ROPT_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RGPR_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RGPT_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RGPR_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RGPT_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RWPR_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RWPT_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RWPR_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RWPT_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RWIR_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC GL  NOT RECOGNISED                              
 IN KEYWORD RWIT_GL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RWIR_NL                                                      
</error>
<error date="6/11/1997" time="0.00000000000000">
 FLUID-IN-PLACE MNEMONIC NL  NOT RECOGNISED                              
 IN KEYWORD RWIT_NL                                                      
</error>
<message date="6/11/1997" time="0.00000000000000">
 DRSDT CONSTRAINT ENABLED FOR RESERVOIR                                  
 WITH DISSOLVED GAS AND VAPOURISED OIL.                                  
</message>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE   5 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   10   1   6   5   1              
 THE BHP =   2.64090E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE   6 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   10   1   3   6   1              
 THE BHP =   1.95620E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE   3 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   19   1   1   8   1              
 THE BHP =   3.31239E+03   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  38 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   18   1   2   8   1              
 THE BHP =   7.99290E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  39 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   18   1   1   7   1              
 THE BHP =   9.40180E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  40 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   17   1   3   7   1              
 THE BHP =   5.83550E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  41 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   18   1   8   7   1              
 THE BHP =   8.28170E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  42 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   18   1   7   7   1              
 THE BHP =   9.25500E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  43 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   16   8   1   8   1              
 THE BHP =   2.39790E+03   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  47 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   18   1   1   8   1              
 THE BHP =   1.44052E+03   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE   9 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =    4   1   6   9   1              
 THE BHP =   6.92020E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  31 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =    6   1   4   8   1              
 THE BHP =   2.76070E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  32 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   10   1   7   9   1              
 THE BHP =   5.30210E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  33 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =    6   1   3   9   1              
 THE BHP =   4.17480E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  34 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =    7   1   7   9   1              
 THE BHP =   2.36860E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  35 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   12   3   4   8   1              
 THE BHP =   5.69330E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 PRODUCTION WELL VFP TABLE  36 CONTAINS AT LEAST ONE                     
 POINT WHERE THE BHP INCREASES WITH DECREASING THP.                      
 AT POINT (FLOW, THP, WFR, GFR, ALQ) =   10   1   2   7   1              
 THE BHP =   3.52500E+02   BARSA .                                       
 IF THIS BHP VALUE INDICATES THE FLOW IS CHOKED OR                       
 EXCEEDS EROSION VELOCITY LIMITS, IT MAY BE CORRECT                      
 AND THE CHECK MAY BE THRESHOLDED WITH KEYWORD VFPCHK.                   
 OTHERWISE YOU SHOULD EXAMINE THE TABLE WITH VFPi AS                     
 IT COULD CAUSE WELL CONVERGENCE OR HUNTING PROBLEMS.                    
</warning>
<warning date="6/11/1997" time="0.00000000000000">
 SPURIOUS DATA BEFORE ZIPPY2   KEYWORD                                   
 /                                                                       
</warning>
<message date="6/11/1997" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<warning date="6/11/1997" time="0.00000000000000">
 PREVIOUSLY SPECIFIED DRSDT CONSTRAINT IS NOW                            
 DISABLED BY SPECIFICATION OF VAPPARS KEYWORD                            
</warning>
<message date="6/11/1997" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<warning date="14/11/1997" time="8.00000001157407">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="29/3/1998" time="143.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL B-4H                            
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="26/5/1998" time="201.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL D-4H                            
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="23/6/1998" time="229.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="23/6/1998" time="229.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL C-4H                            
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS    6891.   BARSA               
</warning>
<warning date="30/8/1998" time="297.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL E-3H                            
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="28/9/1998" time="326.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="13/10/1998" time="341.00000000000000">
 WELL C-4H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="4/1/1999" time="424.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="19/1/1999" time="439.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="21/1/1999" time="441.00000000000000">
 THE PREFERRED PHASE FOR WELL C-2H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="24/2/1999" time="475.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="5/3/1999" time="484.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="23/3/1999" time="502.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="4/5/1999" time="544.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="20/5/1999" time="560.00000000000000">
 THE PREFERRED PHASE FOR WELL F-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="3/10/1999" time="696.00000000000000">
 THE PREFERRED PHASE FOR WELL F-2H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="16/10/1999" time="709.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="9/11/1999" time="733.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="10/11/1999" time="734.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="2/3/2000" time="847.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL E-4H                            
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="2/8/2000" time="1000.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL D-3H                            
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="9/9/2000" time="1038.00000000000000">
 THE PREFERRED PHASE FOR WELL F-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="6/6/2001" time="1308.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL B-4AH                           
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="18/6/2001" time="1320.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="18/6/2001" time="1320.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="19/6/2001" time="1321.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="2/7/2001" time="1334.00000000000000">
 THE PREFERRED PHASE FOR WELL F-4H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="16/8/2001" time="1379.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="10/9/2001" time="1404.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="29/12/2001" time="1514.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="1/5/2002" time="1637.00000000000000">
 WELL D-1H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="8/7/2002" time="1705.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="11/7/2002" time="1708.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="15/7/2002" time="1712.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="14/8/2002" time="1742.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="14/8/2002" time="1742.00000000000000">
 WELL D-1H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="1/9/2002" time="1760.00000000000000">
 WELL D-1H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="2/9/2002" time="1761.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="2/9/2002" time="1761.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="7/10/2002" time="1796.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="14/10/2002" time="1803.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="24/12/2002" time="1874.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="2/1/2003" time="1883.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="12/1/2003" time="1893.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="20/1/2003" time="1901.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="14/2/2003" time="1926.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="6/3/2003" time="1946.00000000000000">
 WELL B-3H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="10/7/2003" time="2072.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="10/7/2003" time="2072.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="12/8/2003" time="2105.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="12/8/2003" time="2105.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="2/9/2003" time="2126.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="10/9/2003" time="2134.00000000000000">
 WELL B-1H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="1/10/2003" time="2155.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="8/12/2003" time="2223.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4AH    IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="18/12/2003" time="2233.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="19/1/2004" time="2265.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="25/7/2004" time="2453.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="20/9/2004" time="2510.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="12/1/2005" time="2624.00000000000000">
 WELL E-3AH    IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="26/1/2005" time="2638.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="26/1/2005" time="2638.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4AH    IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="23/3/2005" time="2694.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL E-3BH                           
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="2/6/2005" time="2765.00000000000000">
 WELL D-3AH    IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<warning date="26/6/2005" time="2789.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4AH    IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="10/7/2005" time="2803.00000000000000">
 WELL E-2H     IS OPEN BUT ALL ITS CONNECTIONS                           
 ARE CLOSED.  THE WELL WILL THEREFORE BE SHUT.                           
</warning>
<comment date="4/8/2005" time="2828.00000000000000">
  HEEL TO TOE CONNECTION ORDERING FAILED FOR WELL D-3BH                  
  AND THE ORDERING WILL DEFAULT TO DEPTH. IF YOU                         
  HAVE SUPPLIED THE CONNECTIONS IN THE CORRECT ORDER,                    
  YOU MAY USE THE INPUT OPTION OF THE COMPORD KEYWORD                    
</comment>
<warning date="1/12/2005" time="2947.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL B-1AH                           
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
<warning date="16/8/2006" time="3205.00000000000000">
 THE PREFERRED PHASE FOR WELL C-1H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="16/8/2006" time="3205.00000000000000">
 THE PREFERRED PHASE FOR WELL C-3H     IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="16/8/2006" time="3205.00000000000000">
 THE PREFERRED PHASE FOR WELL C-4AH    IS RE-SET                         
 TO GAS   FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<warning date="14/9/2006" time="3234.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL K-3H                            
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
      1.0   BARSA                                                        
</warning>
</eclipse>
