<eclipse>
<message date="9/4/2015" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="9/4/2015" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="9/4/2015" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      11969 KBYTES                                                       
</message>
<warning date="9/4/2015" time="0.00000000000000">
 SPURIOUS DATA BEFORE PROPS    KEYWORD                                   
 /                                                                       
</warning>
<message date="9/4/2015" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 TRANSMISSIBILITIES TO BE CALCULATED                                     
 USING  NEWTRAN                                                          
</message>
<message date="9/4/2015" time="0.00000000000000">
 180 NON-NEIGHBOUR CONNECTIONS PRESENT                                   
</message>
<comment date="9/4/2015" time="0.00000000000000">
 LEFT HANDED GRIDS MAY NOT BE SUPPORTED                                  
  IN ALL PRE AND POST PROCESSORS                                         
</comment>
<message date="9/4/2015" time="0.00000000000000">
          300 NON-NEIGHBOUR CONNECTIONS PRESENT                          
      IN LOCAL GRID CENTER                                               
</message>
<comment date="9/4/2015" time="0.00000000000000">
 LEFT HANDED GRIDS MAY NOT BE SUPPORTED                                  
  IN ALL PRE AND POST PROCESSORS                                         
</comment>
<comment date="9/4/2015" time="0.00000000000000">
 LEFT HANDED GRIDS MAY NOT BE SUPPORTED                                  
  IN ALL PRE AND POST PROCESSORS                                         
</comment>
<message date="9/4/2015" time="0.00000000000000">
 LGR WORKSPACE USED:                                                     
    81089 INTEGERS,    20388 REALS   (TOTAL   487460 BYTES)              
 LGR WORKSPACE ALLOCATED:                                                
    81107 INTEGERS,    20389 REALS   (TOTAL   487540 BYTES)              
 MINIMUM POSSIBLE RUNSPEC VALUES IN LGR FOR THIS RUN ARE:                
 MAXLGR  =    2     MAXCLS  =   3600                                     
 NOTE: NO. OF CELLS IN ANY LOCAL GRID CANNOT EXCEED MAXCLS               
</message>
<message date="9/4/2015" time="0.00000000000000">
 NUMBER OF ACTIVE GLOBAL CELLS IS 4000                                   
 NUMBER OF ACTIVE  LOCAL CELLS IS 5220                                   
  TOTAL NUMBER OF ACTIVE CELLS IS 9220                                   
</message>
<message date="9/4/2015" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
      19139 KBYTES                                                       
</message>
<message date="9/4/2015" time="0.00000000000000">
    62375 CHARACTER VARIABLES USED                                       
</message>
<warning date="9/4/2015" time="0.00000000000000">
 TRACER NAMES STARTING WITH A BLANK SPACE OR ANY OF THE                  
 CHARACTERS F, S OR T ARE NOT RECOMMENDED SINCE THIS MAY CREATE          
 NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER: 'TR1'                   
</warning>
<warning date="9/4/2015" time="0.00000000000000">
 TRACER NAMES STARTING WITH A BLANK SPACE OR ANY OF THE                  
 CHARACTERS F, S OR T ARE NOT RECOMMENDED SINCE THIS MAY CREATE          
 NAMING AMBIGUITIES FOR POST-PROCESSORS. TRACER: 'TR2'                   
</warning>
<message date="9/4/2015" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SCHEDULE SECTION IS                  
      20378 KBYTES                                                       
</message>
<message date="9/4/2015" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<message date="24/4/2015" time="15.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
</message>
<message date="9/5/2015" time="30.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
</message>
<message date="24/5/2015" time="45.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
</message>
<message date="8/6/2015" time="60.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
</message>
<message date="23/6/2015" time="75.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
</message>
<message date="8/7/2015" time="90.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
</message>
<message date="23/7/2015" time="105.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
</message>
<message date="7/8/2015" time="120.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
</message>
<message date="22/8/2015" time="135.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
</message>
<message date="6/9/2015" time="150.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
</message>
<message date="21/9/2015" time="165.00000000000000">
 RESTART FILE WRITTEN   REPORT    11                                     
</message>
<message date="6/10/2015" time="180.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
</message>
<message date="21/10/2015" time="195.00000000000000">
 RESTART FILE WRITTEN   REPORT    13                                     
</message>
<message date="5/11/2015" time="210.00000000000000">
 RESTART FILE WRITTEN   REPORT    14                                     
</message>
<message date="20/11/2015" time="225.00000000000000">
 RESTART FILE WRITTEN   REPORT    15                                     
</message>
<message date="5/12/2015" time="240.00000000000000">
 RESTART FILE WRITTEN   REPORT    16                                     
</message>
<message date="20/12/2015" time="255.00000000000000">
 RESTART FILE WRITTEN   REPORT    17                                     
</message>
<message date="4/1/2016" time="270.00000000000000">
 RESTART FILE WRITTEN   REPORT    18                                     
</message>
<message date="19/1/2016" time="285.00000000000000">
 RESTART FILE WRITTEN   REPORT    19                                     
</message>
<message date="3/2/2016" time="300.00000000000000">
 RESTART FILE WRITTEN   REPORT    20                                     
</message>
<message date="18/2/2016" time="315.00000000000000">
 RESTART FILE WRITTEN   REPORT    21                                     
</message>
<message date="4/3/2016" time="330.00000000000000">
 RESTART FILE WRITTEN   REPORT    22                                     
</message>
<message date="19/3/2016" time="345.00000000000000">
 RESTART FILE WRITTEN   REPORT    23                                     
</message>
<message date="3/4/2016" time="360.00000000000000">
 RESTART FILE WRITTEN   REPORT    24                                     
</message>
<message date="3/5/2016" time="390.00000000000000">
 RESTART FILE WRITTEN   REPORT    25                                     
</message>
<message date="2/6/2016" time="420.00000000000000">
 RESTART FILE WRITTEN   REPORT    26                                     
</message>
<message date="2/7/2016" time="450.00000000000000">
 RESTART FILE WRITTEN   REPORT    27                                     
</message>
<message date="1/8/2016" time="480.00000000000000">
 RESTART FILE WRITTEN   REPORT    28                                     
</message>
<message date="31/8/2016" time="510.00000000000000">
 RESTART FILE WRITTEN   REPORT    29                                     
</message>
<message date="30/9/2016" time="540.00000000000000">
 RESTART FILE WRITTEN   REPORT    30                                     
</message>
<message date="30/10/2016" time="570.00000000000000">
 RESTART FILE WRITTEN   REPORT    31                                     
</message>
<message date="29/11/2016" time="600.00000000000000">
 RESTART FILE WRITTEN   REPORT    32                                     
</message>
<message date="29/12/2016" time="630.00000000000000">
 RESTART FILE WRITTEN   REPORT    33                                     
</message>
<message date="28/1/2017" time="660.00000000000000">
 RESTART FILE WRITTEN   REPORT    34                                     
</message>
<message date="27/2/2017" time="690.00000000000000">
 RESTART FILE WRITTEN   REPORT    35                                     
</message>
<message date="29/3/2017" time="720.00000000000000">
 RESTART FILE WRITTEN   REPORT    36                                     
</message>
</eclipse>
