<eclipse>
<warning date="19/10/1982" time="0.00000000000000">
 THE NUMBER OF WELLS HAS BEEN DEFAULTED TO ZERO                          
 USING KEYWORD WELLDIMS IN THE RUNSPEC SECTION                           
 OR NO WELLS WERE FOUND IN THE SCHEDULE SECTION                          
</warning>
<message date="19/10/1982" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="19/10/1982" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="19/10/1982" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     125388 BYTES                                                        
</message>
<warning date="19/10/1982" time="0.00000000000000">
          200 VALUES NOT DEFINED IN BOX (  1- 10,  1- 10,  1-  3)        
 OF KEYWORD TOPS                                                         
</warning>
<message date="19/10/1982" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="19/10/1982" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<message date="19/10/1982" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 300                                           
</message>
<message date="19/10/1982" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     666160 BYTES                                                        
</message>
<message date="19/10/1982" time="0.00000000000000">
    58530 CHARACTER VARIABLES USED                                       
</message>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   6531.94138 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.01230                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   6842.28621 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.07111                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7152.63103 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.12539                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7462.97586 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.17567                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7773.32069 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.22244                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8083.66552 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.26608                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8394.01034 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.30695                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8704.35517 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.34534                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   9014.70000 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.38150                              
</warning>
<warning date="19/10/1982" time="0.00000000000000">
 THE CONVERGENCE TOLERANCES ARE RATHER LARGE                             
 IN KEYWORD TUNING. THIS MAY CAUSE UNPHYSICAL                            
 SOLUTIONS AND LONGER RUNTIMES                                           
</warning>
<message date="19/10/1982" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<message date="19/10/1982" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<message date="20/10/1982" time="1.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="3/11/1982" time="15.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="28/11/1982" time="40.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="23/12/1982" time="65.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="17/1/1983" time="90.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="11/2/1983" time="115.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="8/3/1983" time="140.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="2/4/1983" time="165.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="27/4/1983" time="190.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="22/5/1983" time="215.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="16/6/1983" time="240.00000000000000">
 RESTART FILE WRITTEN   REPORT    11                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="11/7/1983" time="265.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="5/8/1983" time="290.00000000000000">
 RESTART FILE WRITTEN   REPORT    13                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="30/8/1983" time="315.00000000000000">
 RESTART FILE WRITTEN   REPORT    14                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="24/9/1983" time="340.00000000000000">
 RESTART FILE WRITTEN   REPORT    15                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="19/10/1983" time="365.00000000000000">
 RESTART FILE WRITTEN   REPORT    16                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="8/11/1983" time="385.00000000000000">
 RESTART FILE WRITTEN   REPORT    17                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="28/11/1983" time="405.00000000000000">
 RESTART FILE WRITTEN   REPORT    18                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="18/12/1983" time="425.00000000000000">
 RESTART FILE WRITTEN   REPORT    19                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="7/1/1984" time="445.00000000000000">
 RESTART FILE WRITTEN   REPORT    20                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="27/1/1984" time="465.00000000000000">
 RESTART FILE WRITTEN   REPORT    21                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="16/2/1984" time="485.00000000000000">
 RESTART FILE WRITTEN   REPORT    22                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="7/3/1984" time="505.00000000000000">
 RESTART FILE WRITTEN   REPORT    23                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="27/3/1984" time="525.00000000000000">
 RESTART FILE WRITTEN   REPORT    24                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="16/4/1984" time="545.00000000000000">
 RESTART FILE WRITTEN   REPORT    25                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="6/5/1984" time="565.00000000000000">
 RESTART FILE WRITTEN   REPORT    26                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="26/5/1984" time="585.00000000000000">
 RESTART FILE WRITTEN   REPORT    27                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="15/6/1984" time="605.00000000000000">
 RESTART FILE WRITTEN   REPORT    28                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="5/7/1984" time="625.00000000000000">
 RESTART FILE WRITTEN   REPORT    29                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="18/7/1984" time="638.00000000000000">
 RESTART FILE WRITTEN   REPORT    30                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="31/7/1984" time="651.00000000000000">
 RESTART FILE WRITTEN   REPORT    31                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="13/8/1984" time="664.00000000000000">
 RESTART FILE WRITTEN   REPORT    32                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="26/8/1984" time="677.00000000000000">
 RESTART FILE WRITTEN   REPORT    33                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="8/9/1984" time="690.00000000000000">
 RESTART FILE WRITTEN   REPORT    34                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="21/9/1984" time="703.00000000000000">
 RESTART FILE WRITTEN   REPORT    35                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="4/10/1984" time="716.00000000000000">
 RESTART FILE WRITTEN   REPORT    36                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
<message date="18/10/1984" time="730.00000000000000">
 RESTART FILE WRITTEN   REPORT    37                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  FLUIDS IN PLACE                                        
</message>
</eclipse>
